[2022-04-20T10:31:37.254573+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:8000/"" at C:\laragon\www\Symfony\gitebis\vendor\symfony\http-kernel\EventListener\RouterListener.php line 135 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:8000/\" at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:135)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:186)"} []
[2022-04-20T10:31:37.271463+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T10:31:37.279239+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T10:31:37.867801+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"9ed709"},"request_uri":"http://localhost:8000/_wdt/9ed709","method":"GET"} []
[2022-04-20T10:39:38.611423+00:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://localhost:8000/lucky/number","method":"GET"} []
[2022-04-20T10:39:38.614620+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-20T10:39:38.646955+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T10:39:38.656299+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T10:39:39.453065+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"19383e"},"request_uri":"http://localhost:8000/_wdt/19383e","method":"GET"} []
[2022-04-20T10:40:20.236666+00:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://localhost:8000/lucky/number","method":"GET"} []
[2022-04-20T10:40:20.246220+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-20T10:40:20.342582+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T10:40:20.351611+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T10:40:20.945482+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"79f779"},"request_uri":"http://localhost:8000/_wdt/79f779","method":"GET"} []
[2022-04-20T10:40:46.375461+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:8000/lucky/number/45"" at C:\laragon\www\Symfony\gitebis\vendor\symfony\http-kernel\EventListener\RouterListener.php line 135 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:8000/lucky/number/45\" at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:135)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/lucky/number/45/\". at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:74)"} []
[2022-04-20T10:40:46.615163+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T10:40:46.623067+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T10:40:46.625055+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T10:40:46.628636+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T10:40:47.331151+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"ddbada"},"request_uri":"http://localhost:8000/_wdt/ddbada","method":"GET"} []
[2022-04-20T10:41:25.263678+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:8000/lucky/78"" at C:\laragon\www\Symfony\gitebis\vendor\symfony\http-kernel\EventListener\RouterListener.php line 135 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:8000/lucky/78\" at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:135)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/lucky/78/\". at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:74)"} []
[2022-04-20T10:41:25.404149+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T10:41:25.411354+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T10:41:25.414027+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T10:41:25.434578+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T10:41:26.068719+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"c9acca"},"request_uri":"http://localhost:8000/_wdt/c9acca","method":"GET"} []
[2022-04-20T10:41:35.257432+00:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://localhost:8000/lucky/number","method":"GET"} []
[2022-04-20T10:41:35.265355+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-20T10:41:35.362913+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T10:41:35.369728+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T10:41:35.725619+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"835976"},"request_uri":"http://localhost:8000/_wdt/835976","method":"GET"} []
[2022-04-20T12:34:37.283339+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "[Semantical Error] The annotation "@Route" in method App\Controller\LuckyController::number() was never imported. Did you maybe forget to add a "use" statement for this annotation? in C:\laragon\www\Symfony\gitebis\config/routes\../../src/Controller/ (which is being imported from "C:\laragon\www\Symfony\gitebis\config/routes/annotations.yaml"). Make sure to use PHP 8+ or that annotations are installed and enabled." at C:\laragon\www\Symfony\gitebis\vendor\symfony\config\Loader\FileLoader.php line 174 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\LuckyController::number() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\laragon\\www\\Symfony\\gitebis\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\laragon\\www\\Symfony\\gitebis\\config/routes/annotations.yaml\"). Make sure to use PHP 8+ or that annotations are installed and enabled. at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\config\\Loader\\FileLoader.php:174)\n[previous exception] [object] (Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\LuckyController::number() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationException.php:39)"} []
[2022-04-20T12:34:37.532701+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T12:34:37.564724+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T12:34:37.573422+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T12:34:37.578131+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T12:34:38.357336+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "[Semantical Error] The annotation "@Route" in method App\Controller\LuckyController::number() was never imported. Did you maybe forget to add a "use" statement for this annotation? in C:\laragon\www\Symfony\gitebis\config/routes\../../src/Controller/ (which is being imported from "C:\laragon\www\Symfony\gitebis\config/routes/annotations.yaml"). Make sure to use PHP 8+ or that annotations are installed and enabled." at C:\laragon\www\Symfony\gitebis\vendor\symfony\config\Loader\FileLoader.php line 174 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\LuckyController::number() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\laragon\\www\\Symfony\\gitebis\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\laragon\\www\\Symfony\\gitebis\\config/routes/annotations.yaml\"). Make sure to use PHP 8+ or that annotations are installed and enabled. at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\config\\Loader\\FileLoader.php:174)\n[previous exception] [object] (Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\LuckyController::number() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationException.php:39)"} []
[2022-04-20T12:34:38.584971+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T12:34:38.592823+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T12:34:38.602419+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T12:34:38.605728+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T12:34:38.961730+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "[Semantical Error] The annotation "@Route" in method App\Controller\LuckyController::number() was never imported. Did you maybe forget to add a "use" statement for this annotation? in C:\laragon\www\Symfony\gitebis\config/routes\../../src/Controller/ (which is being imported from "C:\laragon\www\Symfony\gitebis\config/routes/annotations.yaml"). Make sure to use PHP 8+ or that annotations are installed and enabled." at C:\laragon\www\Symfony\gitebis\vendor\symfony\config\Loader\FileLoader.php line 174 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\LuckyController::number() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\laragon\\www\\Symfony\\gitebis\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\laragon\\www\\Symfony\\gitebis\\config/routes/annotations.yaml\"). Make sure to use PHP 8+ or that annotations are installed and enabled. at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\config\\Loader\\FileLoader.php:174)\n[previous exception] [object] (Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\LuckyController::number() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationException.php:39)"} []
[2022-04-20T12:34:39.175573+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T12:34:39.187848+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T12:34:39.197129+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T12:34:39.201772+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T13:02:21.313108+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "[Semantical Error] The annotation "@Route" in method App\Controller\LuckyController::number() was never imported. Did you maybe forget to add a "use" statement for this annotation? in C:\laragon\www\Symfony\gitebis\config/routes\../../src/Controller/ (which is being imported from "C:\laragon\www\Symfony\gitebis\config/routes/annotations.yaml"). Make sure to use PHP 8+ or that annotations are installed and enabled." at C:\laragon\www\Symfony\gitebis\vendor\symfony\config\Loader\FileLoader.php line 174 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\LuckyController::number() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\laragon\\www\\Symfony\\gitebis\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\laragon\\www\\Symfony\\gitebis\\config/routes/annotations.yaml\"). Make sure to use PHP 8+ or that annotations are installed and enabled. at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\config\\Loader\\FileLoader.php:174)\n[previous exception] [object] (Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\LuckyController::number() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationException.php:39)"} []
[2022-04-20T13:02:21.549434+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T13:02:21.560141+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T13:02:21.568131+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T13:02:21.572912+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T13:02:25.844334+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "[Semantical Error] The annotation "@Route" in method App\Controller\LuckyController::number() was never imported. Did you maybe forget to add a "use" statement for this annotation? in C:\laragon\www\Symfony\gitebis\config/routes\../../src/Controller/ (which is being imported from "C:\laragon\www\Symfony\gitebis\config/routes/annotations.yaml"). Make sure to use PHP 8+ or that annotations are installed and enabled." at C:\laragon\www\Symfony\gitebis\vendor\symfony\config\Loader\FileLoader.php line 174 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\LuckyController::number() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\laragon\\www\\Symfony\\gitebis\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\laragon\\www\\Symfony\\gitebis\\config/routes/annotations.yaml\"). Make sure to use PHP 8+ or that annotations are installed and enabled. at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\config\\Loader\\FileLoader.php:174)\n[previous exception] [object] (Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\LuckyController::number() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationException.php:39)"} []
[2022-04-20T13:02:26.056465+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T13:02:26.065794+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T13:02:26.073787+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T13:02:26.100397+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T13:05:05.050350+00:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://localhost:8000/lucky/number","method":"GET"} []
[2022-04-20T13:05:05.055084+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-20T13:05:05.094422+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T13:05:05.101142+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T13:05:05.759445+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"69f000"},"request_uri":"http://localhost:8000/_wdt/69f000","method":"GET"} []
[2022-04-20T13:32:58.333112+00:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://localhost:8000/lucky/number","method":"GET"} []
[2022-04-20T13:32:58.346105+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-20T13:32:58.451106+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T13:32:58.462498+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T13:32:59.102691+00:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://localhost:8000/lucky/number","method":"GET"} []
[2022-04-20T13:32:59.111159+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-20T13:32:59.194449+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T13:32:59.200510+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T13:32:59.600555+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"00e2d0"},"request_uri":"http://localhost:8000/_wdt/00e2d0","method":"GET"} []
[2022-04-20T13:34:14.216277+00:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://localhost:8000/lucky/number","method":"GET"} []
[2022-04-20T13:34:14.225196+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-20T13:34:14.307455+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T13:34:14.313982+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T13:34:14.842147+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"f26e55"},"request_uri":"http://localhost:8000/_wdt/f26e55","method":"GET"} []
[2022-04-20T13:34:17.017250+00:00] request.INFO: Matched route "_profiler". {"route":"_profiler","route_parameters":{"_route":"_profiler","_controller":"web_profiler.controller.profiler::panelAction","token":"f26e55"},"request_uri":"http://localhost:8000/_profiler/f26e55?panel=logger","method":"GET"} []
[2022-04-20T13:34:47.294213+00:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://localhost:8000/lucky/number","method":"GET"} []
[2022-04-20T13:34:47.301262+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-20T13:34:47.389682+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T13:34:47.397159+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T13:34:47.919172+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"c8aae6"},"request_uri":"http://localhost:8000/_wdt/c8aae6","method":"GET"} []
[2022-04-20T13:34:54.416554+00:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://localhost:8000/lucky/number","method":"GET"} []
[2022-04-20T13:34:54.428211+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-20T13:34:54.514560+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T13:34:54.522458+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T13:34:54.866137+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"549206"},"request_uri":"http://localhost:8000/_wdt/549206","method":"GET"} []
[2022-04-20T13:34:56.317845+00:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://localhost:8000/lucky/number","method":"GET"} []
[2022-04-20T13:34:56.325998+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-20T13:34:56.412900+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-20T13:34:56.420596+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-20T13:34:56.747963+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b522ab"},"request_uri":"http://localhost:8000/_wdt/b522ab","method":"GET"} []
[2022-04-21T07:59:19.646780+00:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://localhost:8000/lucky/number","method":"GET"} []
[2022-04-21T07:59:19.682129+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-21T07:59:20.216792+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T07:59:22.400001+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T07:59:22.854712+00:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://localhost:8000/lucky/number","method":"GET"} []
[2022-04-21T07:59:22.863926+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-21T07:59:22.953959+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T07:59:24.992282+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T07:59:25.573417+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"a3cf61"},"request_uri":"http://localhost:8000/_wdt/a3cf61","method":"GET"} []
[2022-04-21T07:59:26.024695+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:8000/favicon.ico" (from "http://localhost:8000/lucky/number")" at C:\laragon\www\Symfony\gitebis\vendor\symfony\http-kernel\EventListener\RouterListener.php line 135 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:8000/favicon.ico\" (from \"http://localhost:8000/lucky/number\") at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:135)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:74)"} []
[2022-04-21T07:59:26.521818+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T07:59:28.551270+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T07:59:28.553150+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T07:59:30.591670+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T07:59:31.382010+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:8000/lucky/page/" (from "http://localhost:8000/lucky/number")" at C:\laragon\www\Symfony\gitebis\vendor\symfony\http-kernel\EventListener\RouterListener.php line 135 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:8000/lucky/page/\" (from \"http://localhost:8000/lucky/number\") at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:135)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/lucky/page\". at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:74)"} []
[2022-04-21T07:59:31.509042+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T07:59:33.542021+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T07:59:33.543884+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T07:59:35.606661+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T07:59:36.133759+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"ba3ae0"},"request_uri":"http://localhost:8000/_wdt/ba3ae0","method":"GET"} []
[2022-04-21T08:00:46.803448+00:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://localhost:8000/lucky/number","method":"GET"} []
[2022-04-21T08:00:46.812004+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-21T08:00:46.897675+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T08:00:48.950536+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T08:00:49.300561+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"1e47a5"},"request_uri":"http://localhost:8000/_wdt/1e47a5","method":"GET"} []
[2022-04-21T08:00:53.401899+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:8000/page/" (from "http://localhost:8000/lucky/number")" at C:\laragon\www\Symfony\gitebis\vendor\symfony\http-kernel\EventListener\RouterListener.php line 135 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:8000/page/\" (from \"http://localhost:8000/lucky/number\") at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:135)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/page\". at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:74)"} []
[2022-04-21T08:00:53.535208+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T08:00:55.588415+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T08:00:55.590309+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T08:00:57.628018+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T08:00:58.091522+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"2c787f"},"request_uri":"http://localhost:8000/_wdt/2c787f","method":"GET"} []
[2022-04-21T08:01:17.203031+00:00] request.INFO: Matched route "app_new_page". {"route":"app_new_page","route_parameters":{"_route":"app_new_page","_controller":"App\\Controller\\PageController::index"},"request_uri":"http://localhost:8000/page/index","method":"GET"} []
[2022-04-21T08:01:17.210289+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-21T08:01:17.302884+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T08:01:19.333896+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.\r\n at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T08:01:19.760936+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"cbd77b"},"request_uri":"http://localhost:8000/_wdt/cbd77b","method":"GET"} []
[2022-04-21T10:23:28.317301+00:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://localhost:8000/lucky/number","method":"GET"} []
[2022-04-21T10:23:28.326349+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-21T10:23:28.467917+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T10:23:28.478509+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T10:23:28.957999+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"bd36c4"},"request_uri":"http://localhost:8000/_wdt/bd36c4","method":"GET"} []
[2022-04-21T10:23:39.927015+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:8000/page/" (from "http://localhost:8000/lucky/number")" at C:\laragon\www\Symfony\gitebis\vendor\symfony\http-kernel\EventListener\RouterListener.php line 135 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:8000/page/\" (from \"http://localhost:8000/lucky/number\") at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:135)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/page\". at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:74)"} []
[2022-04-21T10:23:40.067843+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T10:23:40.089487+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T10:23:40.091412+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T10:23:40.096204+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T10:23:40.585450+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"37f1cb"},"request_uri":"http://localhost:8000/_wdt/37f1cb","method":"GET"} []
[2022-04-21T10:24:03.145620+00:00] request.INFO: Matched route "app_new_page". {"route":"app_new_page","route_parameters":{"_route":"app_new_page","_controller":"App\\Controller\\PageController::index"},"request_uri":"http://localhost:8000/page/index","method":"GET"} []
[2022-04-21T10:24:03.153048+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-21T10:24:03.231187+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T10:24:03.255213+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T10:24:03.674305+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"53e989"},"request_uri":"http://localhost:8000/_wdt/53e989","method":"GET"} []
[2022-04-21T10:24:57.353320+00:00] request.INFO: Matched route "app_new_page". {"route":"app_new_page","route_parameters":{"_route":"app_new_page","_controller":"App\\Controller\\PageController::index"},"request_uri":"http://localhost:8000/page/","method":"GET"} []
[2022-04-21T10:24:57.363309+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-21T10:24:57.446825+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T10:24:57.474105+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T10:24:57.890742+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"4b5d95"},"request_uri":"http://localhost:8000/_wdt/4b5d95","method":"GET"} []
[2022-04-21T11:32:34.400082+00:00] request.INFO: Matched route "page". {"route":"page","route_parameters":{"_route":"page","_controller":"App\\Controller\\PageController::index"},"request_uri":"http://localhost:8000/page/","method":"GET"} []
[2022-04-21T11:32:34.410715+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-21T11:32:34.509909+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T11:32:34.518256+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T11:32:35.086422+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"adf8a2"},"request_uri":"http://localhost:8000/_wdt/adf8a2","method":"GET"} []
[2022-04-21T11:32:44.724792+00:00] request.INFO: Matched route "page". {"route":"page","route_parameters":{"_route":"page","_controller":"App\\Controller\\PageController::index"},"request_uri":"http://localhost:8000/page/","method":"GET"} []
[2022-04-21T11:32:44.733758+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-21T11:32:44.828415+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T11:32:44.838609+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T11:32:45.185431+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"016c14"},"request_uri":"http://localhost:8000/_wdt/016c14","method":"GET"} []
[2022-04-21T11:33:14.192981+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:8000/page/1"" at C:\laragon\www\Symfony\gitebis\vendor\symfony\http-kernel\EventListener\RouterListener.php line 135 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:8000/page/1\" at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:135)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/page/1/\". at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:74)"} []
[2022-04-21T11:33:14.332121+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T11:33:14.353797+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T11:33:14.355685+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T11:33:14.359057+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T11:33:14.943362+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"9026e3"},"request_uri":"http://localhost:8000/_wdt/9026e3","method":"GET"} []
[2022-04-21T11:50:16.349582+00:00] request.INFO: Matched route "app_lucky_number". {"route":"app_lucky_number","route_parameters":{"_route":"app_lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://localhost:8000/lucky/number","method":"GET"} []
[2022-04-21T11:50:16.352446+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-21T11:50:16.382781+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T11:50:16.390118+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T11:50:17.533269+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:8000/page/index"" at C:\laragon\www\Symfony\gitebis\vendor\symfony\http-kernel\EventListener\RouterListener.php line 135 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost:8000/page/index\" at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:135)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/page/index/\". at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:74)"} []
[2022-04-21T11:50:17.693263+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T11:50:17.701047+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T11:50:17.702971+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T11:50:17.707079+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T11:50:18.325901+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"d54cff"},"request_uri":"http://localhost:8000/_wdt/d54cff","method":"GET"} []
[2022-04-21T11:50:21.902297+00:00] request.INFO: Matched route "page". {"route":"page","route_parameters":{"_route":"page","_controller":"App\\Controller\\PageController::index"},"request_uri":"http://localhost:8000/page/","method":"GET"} []
[2022-04-21T11:50:21.910526+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2022-04-21T11:50:21.999223+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"} {"params":{"url":"<redacted>","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"dbname":"gitebis","serverVersion":"5.7","charset":"utf8mb4"}} []
[2022-04-21T11:50:22.021078+00:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:30)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'gitebis' at C:\\laragon\\www\\Symfony\\gitebis\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:28)"} []
[2022-04-21T11:50:22.418680+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"d4895a"},"request_uri":"http://localhost:8000/_wdt/d4895a","method":"GET"} []
